### ISSUE TITLE
bug: erdantic v1 fails with Generics and `TypeVar`

### ISSUE THREAD

**Issue by mansenfranzen** [drivendataorg/erdantic#114]
Hi @jayqi,

while upgrading to erdantic v1 (see https://github.com/mansenfranzen/autodoc_pydantic/issues/241), I encountered an issue while generating the ERD for the `Response` model as defined below:

```python
from typing import Generic, TypeVar, Optional, List

from pydantic import BaseModel, field_validator

DataT = TypeVar('DataT')


class Error(BaseModel):
    """HTTP error representation."""
    code: int
    message: str


class DataModel(BaseModel):
    """Payload representation."""
    numbers: List[int]
    people: List[str]


class Response(BaseModel, Generic[DataT]):
    """HTTP Response representation."""

    data: Optional[DataT]
    error: Optional[Error]

    @field_validator('error')
    def check_consistency(cls, v, values):
        if v is not None and values['data'] is not None:
            raise ValueError('must not provide both data and error')
        if v is None and values.get('data') is None:
            raise ValueError('must provide data or error')
        return v
```

The error is as follows:

```
# Platform:         linux; (Linux-6.5.0-26-generic-x86_64-with-glibc2.35)
# Sphinx version:   7.1.2
# Python version:   3.10.12 (CPython)
# Docutils version: 0.20.1
# Jinja2 version:   3.1.3
# Pygments version: 2.17.2

# Last messages:
#   users/_autosummary/target.usage_autosummary.AutoSummarySettings
#   

#   reading sources... [ 69%]
#   users/configuration
#   

#   reading sources... [ 77%]
#   users/examples
#   

# Loaded extensions:
#   sphinx.ext.mathjax (7.1.2)
#   alabaster (0.7.13)
#   sphinxcontrib.applehelp (1.0.4)
#   sphinxcontrib.devhelp (1.0.2)
#   sphinxcontrib.htmlhelp (2.0.1)
#   sphinxcontrib.serializinghtml (1.1.5)
#   sphinxcontrib.qthelp (1.0.3)
#   sphinxcontrib.jquery (4.1)
#   sphinx_rtd_theme (unknown version)
#   sphinx.ext.autodoc.preserve_defaults (7.1.2)
#   sphinx.ext.autodoc.type_comment (7.1.2)
#   sphinx.ext.autodoc.typehints (7.1.2)
#   sphinx.ext.autodoc (7.1.2)
#   sphinx.ext.napoleon (7.1.2)
#   sphinx.ext.autosummary (7.1.2)
#   sphinx.ext.graphviz (7.1.2)
#   sphinx_tabs.tabs (unknown version)
#   sphinx_copybutton (0.5.2)
#   sphinxcontrib.autodoc_pydantic (2.1.0)
#   sphinxcontrib.mermaid (7.1.2)
#   sphinx.ext.viewcode (7.1.2)
#   extensions (unknown version)
#   myst_parser (2.0.0)

# Traceback:
Traceback (most recent call last):
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/sphinx/cmd/build.py", line 290, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/sphinx/application.py", line 351, in build
    self.builder.build_update()
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 290, in build_update
    self.build(to_build,
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 310, in build
    updated_docnames = set(self.read())
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 417, in read
    self._read_serial(docnames)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 438, in _read_serial
    self.read_doc(docname)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 494, in read_doc
    publisher.publish()
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/core.py", line 234, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/sphinx/io.py", line 104, in read
    self.parse()
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/sphinx/parsers.py", line 80, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 169, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 3024, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2785, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 3024, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2355, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2367, in explicit_construct
    return method(self, expmatch)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2104, in directive
    return self.run_directive(
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2154, in run_directive
    result = directive_instance.run()
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/sphinx_tabs/tabs.py", line 103, in run
    self.state.nested_parse(self.content, self.content_offset, node)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2355, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2367, in explicit_construct
    return method(self, expmatch)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2104, in directive
    return self.run_directive(
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2154, in run_directive
    result = directive_instance.run()
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/sphinx_tabs/tabs.py", line 187, in run
    self.state.nested_parse(self.content[1:], self.content_offset, panel)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2355, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2367, in explicit_construct
    return method(self, expmatch)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2104, in directive
    return self.run_directive(
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2154, in run_directive
    result = directive_instance.run()
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/sphinx/ext/autodoc/directive.py", line 135, in run
    documenter.generate(more_content=self.content)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 1871, in generate
    return super().generate(more_content=more_content,
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 947, in generate
    self.add_content(more_content)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/sphinxcontrib/autodoc_pydantic/directives/autodocumenters.py", line 285, in add_content
    self.add_erdantic_figure()
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/sphinxcontrib/autodoc_pydantic/directives/autodocumenters.py", line 348, in add_erdantic_figure
    figure_dot = erd.to_dot(self.object, graph_attr={"label": ""}).replace('\t', '   ').split('\n')
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/erdantic/convenience.py", line 184, in to_dot
    diagram = create(
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/erdantic/convenience.py", line 67, in create
    diagram.add_model(mm)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/erdantic/core.py", line 570, in add_model
    is_model = self._add_if_model(model, recurse=recurse)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/erdantic/core.py", line 533, in _add_if_model
    is_model = self._add_if_model(arg, recurse=recurse)
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/erdantic/core.py", line 516, in _add_if_model
    key = str(FullyQualifiedName.from_object(model))
  File "/home/franne/Desktop/franz/python/autodoc_pydantic/.venv/lib/python3.10/site-packages/erdantic/core.py", line 82, in from_object
    return cls(module=obj.__module__, qual_name=obj.__qualname__)
AttributeError: 'TypeVar' object has no attribute '__qualname__'
```

For the time being, I will update the example in the autodoc_pydantic docs (see [here](https://autodoc-pydantic.readthedocs.io/en/stable/users/examples.html#entity-relationship-diagram)) because the current example is not very educative anyway. Hence, I this issue does not block the migration to erdantic v1.

**Comment by jayqi** [comment]
@mansenfranzen 

v1.0.2 is out on PyPI with the fix. Your example should work correctly now.

```python
from typing import Generic, TypeVar, Optional, List

import erdantic as erd
from pydantic import BaseModel, field_validator
import rich

DataT = TypeVar('DataT')


class Error(BaseModel):
    """HTTP error representation."""
    code: int
    message: str


class DataModel(BaseModel):
    """Payload representation."""
    numbers: List[int]
    people: List[str]


class Response(BaseModel, Generic[DataT]):
    """HTTP Response representation."""

    data: Optional[DataT]
    error: Optional[Error]

    @field_validator('error')
    def check_consistency(cls, v, values):
        if v is not None and values['data'] is not None:
            raise ValueError('must not provide both data and error')
        if v is None and values.get('data') is None:
            raise ValueError('must provide data or error')
        return v

diagram = erd.create(Error, DataModel, Response)
rich.print(diagram)
#> EntityRelationshipDiagram(
#>     models={
#>         '__main__.DataModel': ModelInfo(...),
#>         '__main__.Error': ModelInfo(...),
#>         '__main__.Response': ModelInfo(...)
#>     },
#>     edges={'__main__.Response-error-__main__.Error': Edge(...)}
#> )
```
