### ISSUE TITLE
Try run python file

### ISSUE THREAD

**Issue by AlexDemure** [drivendataorg/erdantic#54]
I try run python file by you example 
```
def main():
    import erdantic as erd
    from erdantic.examples.pydantic import Party

    # Easy one-liner
    erd.draw(Party, out="diagram.png")

    # Or create a diagram object that you can inspect and do stuff with
    diagram = erd.create(Party)
    diagram.draw("diagram.png")


if __name__ == '__main__':
    # Easy one-liner
    main()
```
```
Traceback (most recent call last):
  File "/home/alex/work/bustail/backend/schemas/erdantic.py", line 18, in <module>
    main()
  File "/home/alex/work/bustail/backend/schemas/erdantic.py", line 6, in main
    from erdantic.examples.pydantic import Party
ModuleNotFoundError: No module named 'erdantic.examples'; 'erdantic' is not a package
```

**Comment by AlexDemure** [comment]
Try user attributes 
```
from pydantic import BaseModel

class TestSchema(BaseModel):
    x = 1

def main():
    import erdantic

    # Easy one-liner
    erdantic.create(TestSchema)

```
```
Traceback (most recent call last):
  File "/home/alex/work/bustail/backend/schemas/erdantic.py", line 23, in <module>
    main()
  File "/home/alex/work/bustail/backend/schemas/erdantic.py", line 14, in main
    erdantic.create(TestSchema)
AttributeError: module 'erdantic' has no attribute 'create'
```

How use this lib?
