### ISSUE TITLE
No module found error without setting PYTHONPATH

### ISSUE THREAD

**Issue by bhavaniravi** [drivendataorg/erdantic#73]
Logging this issue so that other people don't have to suffer as much as I did.

I copied the same dataclass example into a `newdataclass.py` python file and ran `erdantic newdataclass -o diagram.png` and got the following error.

After about 30 mins of debugging by running 

```
from importlib import import_module
import_module("newdataclass")
```

I figured it was because `PYTHONPATH` wasn't set to the current directory. 

### Solutions

1. Updating the documentation to mention this explicitly
2. Better error message. Only on scrolling I found a whole traceback of exceptions. Importing module, importing class, etc.,

### Error Log

```
Traceback (most recent call last):

  File "/Users/bhavaniravi/.virtualenvs/python-everyday/lib/python3.9/site-packages/erdantic/cli.py", line 131, in import_object_from_name
    return import_module(full_obj_name)

  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load

  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked

ModuleNotFoundError: No module named 'newdataclass'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/Users/bhavaniravi/.virtualenvs/python-everyday/bin/erdantic", line 8, in <module>
    sys.exit(app())

  File "/Users/bhavaniravi/.virtualenvs/python-everyday/lib/python3.9/site-packages/erdantic/cli.py", line 108, in main
    model_or_module_objs = [import_object_from_name(mm) for mm in models_or_modules]

  File "/Users/bhavaniravi/.virtualenvs/python-everyday/lib/python3.9/site-packages/erdantic/cli.py", line 108, in <listcomp>
    model_or_module_objs = [import_object_from_name(mm) for mm in models_or_modules]

  File "/Users/bhavaniravi/.virtualenvs/python-everyday/lib/python3.9/site-packages/erdantic/cli.py", line 135, in import_object_from_name
    module_name, obj_name = full_obj_name.rsplit(".", 1)

ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by jayqi** [comment]
Thanks for reporting this. 

You are correct that the classes you want to diagram must be importable, whether that's by making sure its module is part of your PYTHONPATH or if it's part of an installed package. 

Both of the items you've listed under "Solutions" are good ideas and both would be good to be implemented.

**Comment by jayqi** [comment]
The first paragraph under ["Quick Usage"](https://github.com/drivendataorg/erdantic?tab=readme-ov-file#quick-usage) in the README now notes this. 

Additionally, in v1.0, you now get an exception that is hopefully more clear:

```
$ erdantic something.notinstalled --dot

ModelOrModuleNotFoundError: Unable to import 'something.notinstalled'.
```
