### ISSUE TITLE
Support for Pydantic V2

### ISSUE THREAD

**Issue by treykeown** [drivendataorg/erdantic#82]
Hi! Pydantic V2 just dropped, including a number of breaking changes. Running `erdantic`, I see the following:

```console
$ erdantic
Traceback (most recent call last):
  File ".../src/.venv/bin/erdantic", line 5, in <module>
    from erdantic.cli import app
  File ".../src/.venv/lib/python3.11/site-packages/erdantic/__init__.py", line 2, in <module>
    import erdantic.pydantic  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../src/.venv/lib/python3.11/site-packages/erdantic/pydantic.py", line 11, in <module>
    class PydanticField(Field[pydantic.fields.ModelField]):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pydantic.fields' has no attribute 'ModelField'
```

**Comment by jayqi** [comment]
Just released erdantic v0.5.1, which puts a version ceiling on pydantic of `< 2`. This is a temporary measure to make the compatibility explicit. 

Support for Pydantic V2 in progress.
